### ISSUE TITLE
[Question] Windows binaries

### ISSUE THREAD

**Issue by wagnerpv** [teamprevue/PreVue#83]
Is there any known reason preventing someone from building this electron app on Windows for themselves?

Thanks in advance
W

**Comment by hubelin** [comment]
Hey @wagnerpv, there was additional build config preventing immediate release but I’ll try to get the window version released by today or tomorrow!

- Hubert

**Comment by wagnerpv** [comment]
@hubelin thanks for your prompt reply.

**Comment by hubelin** [comment]
> @hubelin thanks for your prompt reply.

No problem! Windows support just added. Please let me know if any issues

**Comment by wagnerpv** [comment]
oh! Thanks a lot.
