### ISSUE TITLE
How to install and run?

### ISSUE THREAD

**Issue by gawaineo** [teamprevue/PreVue#85]
How can I install and run this tool? I was expecting more instructions in your README.md file.

**Comment by pinnockf** [comment]
Hi Gawaine,

If you would like to run the executable version of this application then you can download it for MacOs, Windows, or Linux at https://www.prevue.io/.

However, if you would like to download and run from the source code the there are instructions further down in the readme in the section titled "Running your own local version" that will get you up and running in on time.

- Franklin
